apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: allianz-demo-canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: allianz-demo-canary
  template:
    metadata:
      labels:
        app: allianz-demo-canary
    spec:
      containers:
      - name: allianz-demo
        image: 623007965873.dkr.ecr.ap-southeast-1.amazonaws.com/allianz-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
  strategy:
    canary:
      canaryService: canary-service
      stableService: stable-service
      trafficRouting:
        alb:
          ingress: ingress
          rootService: root-service
          servicePort: 80
      steps:
      - setWeight: 5
      - pause: {}

---
apiVersion: v1
kind: Service
metadata:
  name: canary-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: allianz-demo-canary

---
apiVersion: v1
kind: Service
metadata:
  name: stable-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: allianz-demo-canary

---
apiVersion: v1
kind: Service
metadata:
  name: root-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: allianz-demo-canary

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.root-service: |
      {
        "Type":"forward",
        "ForwardConfig":{
          "TargetGroups":[
            {
                "Weight":10,
                "ServiceName":"canary-service",
                "ServicePort":"80"
            },
            {
                "Weight":90,
                "ServiceName":"stable-service",
                "ServicePort":"80"
            }
          ]
        }
      }
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Exact
        backend:
          service:
            name: root-service
            port:
              name: use-annotation
